version: '3'

services:

    www:
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - $PWD/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/localhost.pem:/etc/certs/localhost.pem
            - $PWD/localhost-key.pem:/etc/certs/localhost-key.pem
            - $PWD/index.html:/etc/nginx/html/index.html

